module:
  hugoVersion:
    min: "0.61.0"
  mounts:
  - source: layouts/shortcodes
    target: layouts/shortcodes

  imports:
  - path: github.com/mozilla/pdfjs-dist
    mounts:
      - source: build
        target: static/js/pdfjs-dist/build
    mounts:
      - source: web
        target: static/js/pdfjs-dist/web